In [123]:
import numpy as np
import pandas as pd

In [124]:
file = "Dataset\survey_results_public.csv"

<>:1: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
<>:1: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
C:\Users\brpra\AppData\Local\Temp\ipykernel_12640\2360520719.py:1: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
  file = "Dataset\survey_results_public.csv"

In [125]:
df = pd.read_csv(file)

In [126]:
df.head(3)

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult

In [127]:
df.shape

(88883, 85)

In [128]:
df.columns

Index(['Respondent', 'MainBranch', 'Hobbyist', 'OpenSourcer', 'OpenSource',
       'Employment', 'Country', 'Student', 'EdLevel', 'UndergradMajor',
       'EduOther', 'OrgSize', 'DevType', 'YearsCode', 'Age1stCode',
       'YearsCodePro', 'CareerSat', 'JobSat', 'MgrIdiot', 'MgrMoney',
       'MgrWant', 'JobSeek', 'LastHireDate', 'LastInt', 'FizzBuzz',
       'JobFactors', 'ResumeUpdate', 'CurrencySymbol', 'CurrencyDesc',
       'CompTotal', 'CompFreq', 'ConvertedComp', 'WorkWeekHrs', 'WorkPlan',
       'WorkChallenge', 'WorkRemote', 'WorkLoc', 'ImpSyn', 'CodeRev',
       'CodeRevHrs', 'UnitTests', 'PurchaseHow', 'PurchaseWhat',
       'LanguageWorkedWith', 'LanguageDesireNextYear', 'DatabaseWorkedWith',
       'DatabaseDesireNextYear', 'PlatformWorkedWith',
       'PlatformDesireNextYear', 'WebFrameWorkedWith',
       'WebFrameDesireNextYear', 'MiscTechWorkedWith',
       'MiscTechDesireNextYear', 'DevEnviron', 'OpSys', 'Containers',
       'BlockchainOrg', 'BlockchainIs', 'BetterLife', 'ITperson', 'OffOn',
       'SocialMedia', 'Extraversion', 'ScreenName', 'SOVisit1st',
       'SOVisitFreq', 'SOVisitTo', 'SOFindAnswer', 'SOTimeSaved',
       'SOHowMuchTime', 'SOAccount', 'SOPartFreq', 'SOJobs', 'EntTeams',
       'SOComm', 'WelcomeChange', 'SONewContent', 'Age', 'Gender', 'Trans',
       'Sexuality', 'Ethnicity', 'Dependents', 'SurveyLength', 'SurveyEase'],
      dtype='str')

In [129]:
required_columns = [
    "Age1stCode",
    "Country",
    "LanguageWorkedWith",
    "ConvertedComp",
    "LanguageDesireNextYear",
    "Hobbyist",
    "Gender",
    "JobSat",
    "CareerSat"
]

df[required_columns].head()

,Age1stCode,Country,LanguageWorkedWith,ConvertedComp,LanguageDesireNextYear,Hobbyist,Gender,JobSat,CareerSat
0,10,United Kingdom,HTML/CSS;Java;JavaScript;Python,NaN,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,Yes,Man,NaN,NaN
1,17,Bosnia and Herzegovina,C++;HTML/CSS;Python,NaN,C++;HTML/CSS;JavaScript;SQL,No,Man,NaN,NaN
2,22,Thailand,HTML/CSS,8820.0,Elixir;HTML/CSS,Yes,Man,Slightly satisfied,Slightly satisfied
3,16,United States,C;C++;C#;Python;SQL,61000.0,C;C#;JavaScript;SQL,No,Man,Slightly satisfied,Very satisfied
4,14,Ukraine,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA,NaN,HTML/CSS;Java;JavaScript;SQL;WebAssembly,Yes,Man,Slightly dissatisfied,Very dissatisfied

In [130]:
df[required_columns].dtypes

Age1stCode                    str
Country                       str
LanguageWorkedWith            str
ConvertedComp             float64
LanguageDesireNextYear        str
Hobbyist                      str
Gender                        str
JobSat                        str
CareerSat                     str
dtype: object

In [131]:
df[required_columns].isnull().sum()

Age1stCode                 1249
Country                     132
LanguageWorkedWith         1314
ConvertedComp             33060
LanguageDesireNextYear     4795
Hobbyist                      0
Gender                     3477
JobSat                    17895
CareerSat                 16036
dtype: int64

**1. Find the average age of developers when they wrote their first line of code**

In [132]:
df["Age1stCode"].head(10)

0    10
1    17
2    22
3    16
4    14
5    15
6    17
7    16
8    11
9    20
Name: Age1stCode, dtype: str

In [133]:
df["Age1stCode"].isnull().sum()

np.int64(1249)

In [134]:
age_first_code = pd.to_numeric(
    df["Age1stCode"],
    errors="coerce"
)

In [135]:
age_first_code.isnull().sum()

np.int64(1795)

In [136]:
age_first_code.head()

0    10.0
1    17.0
2    22.0
3    16.0
4    14.0
Name: Age1stCode, dtype: float64

In [137]:
age_first_code.dtypes

dtype('float64')

In [138]:
avg = age_first_code.mean()

In [139]:
print("average age of developers", round(avg, 2))

average age of developers 15.46

**2. Deduce the percentage of developers who knew python in each country.**

In [140]:
df.columns

Index(['Respondent', 'MainBranch', 'Hobbyist', 'OpenSourcer', 'OpenSource',
       'Employment', 'Country', 'Student', 'EdLevel', 'UndergradMajor',
       'EduOther', 'OrgSize', 'DevType', 'YearsCode', 'Age1stCode',
       'YearsCodePro', 'CareerSat', 'JobSat', 'MgrIdiot', 'MgrMoney',
       'MgrWant', 'JobSeek', 'LastHireDate', 'LastInt', 'FizzBuzz',
       'JobFactors', 'ResumeUpdate', 'CurrencySymbol', 'CurrencyDesc',
       'CompTotal', 'CompFreq', 'ConvertedComp', 'WorkWeekHrs', 'WorkPlan',
       'WorkChallenge', 'WorkRemote', 'WorkLoc', 'ImpSyn', 'CodeRev',
       'CodeRevHrs', 'UnitTests', 'PurchaseHow', 'PurchaseWhat',
       'LanguageWorkedWith', 'LanguageDesireNextYear', 'DatabaseWorkedWith',
       'DatabaseDesireNextYear', 'PlatformWorkedWith',
       'PlatformDesireNextYear', 'WebFrameWorkedWith',
       'WebFrameDesireNextYear', 'MiscTechWorkedWith',
       'MiscTechDesireNextYear', 'DevEnviron', 'OpSys', 'Containers',
       'BlockchainOrg', 'BlockchainIs', 'BetterLife', 'ITperson', 'OffOn',
       'SocialMedia', 'Extraversion', 'ScreenName', 'SOVisit1st',
       'SOVisitFreq', 'SOVisitTo', 'SOFindAnswer', 'SOTimeSaved',
       'SOHowMuchTime', 'SOAccount', 'SOPartFreq', 'SOJobs', 'EntTeams',
       'SOComm', 'WelcomeChange', 'SONewContent', 'Age', 'Gender', 'Trans',
       'Sexuality', 'Ethnicity', 'Dependents', 'SurveyLength', 'SurveyEase'],
      dtype='str')

In [141]:
df[['Country', 'LanguageWorkedWith']].head()

                  Country                           LanguageWorkedWith
0          United Kingdom              HTML/CSS;Java;JavaScript;Python
1  Bosnia and Herzegovina                          C++;HTML/CSS;Python
2                Thailand                                     HTML/CSS
3           United States                          C;C++;C#;Python;SQL
4                 Ukraine  C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA

In [142]:
q2_df = df[["Country", "LanguageWorkedWith"]].dropna(subset = ["Country"])

In [143]:
q2_df

,Country,LanguageWorkedWith
0,United Kingdom,HTML/CSS;Java;JavaScript;Python
1,Bosnia and Herzegovina,C++;HTML/CSS;Python
2,Thailand,HTML/CSS
3,United States,C;C++;C#;Python;SQL
4,Ukraine,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA
...,...,...
88875,Pakistan,HTML/CSS;Java;JavaScript
88876,Spain,HTML/CSS;JavaScript;Python
88877,United States,Bash/Shell/PowerShell;Go;HTML/CSS;JavaScript;W...
88878,Canada,HTML/CSS;JavaScript;Other(s):
88882,Spain,Bash/Shell/PowerShell;HTML/CSS;Java;JavaScript...

In [144]:
# Developers who knows python
q2_df["KnowsPython"] = (
    q2_df["LanguageWorkedWith"]
    .fillna("")
    .str.split(";")
    .apply(lambda languages: "Python" in languages)
)

In [145]:
#Calculate persentage
q2_report = (
    q2_df.groupby("Country")["KnowsPython"]
    .mean()
    .mul(100)
    .reset_index(name="PythonPercentage")
)

In [146]:
q2_report

                                  Country  PythonPercentage
0                             Afghanistan         18.181818
1                                 Albania         26.744186
2                                 Algeria         29.850746
3                                 Andorra          0.000000
4                                  Angola         40.000000
..                                    ...               ...
174  Venezuela, Bolivarian Republic of...         31.818182
175                              Viet Nam         33.766234
176                                 Yemen         15.789474
177                                Zambia         33.333333
178                              Zimbabwe         35.897436

[179 rows x 2 columns]

**3. Generate the report for the average salary of developers based on the
continent.**

In [147]:
df[["Country", "ConvertedComp"]].head(10)

                  Country  ConvertedComp
0          United Kingdom            NaN
1  Bosnia and Herzegovina            NaN
2                Thailand         8820.0
3           United States        61000.0
4                 Ukraine            NaN
5                  Canada       366420.0
6                 Ukraine            NaN
7                   India            NaN
8             New Zealand        95179.0
9                   India        13293.0

In [148]:
df["ConvertedComp"].dtype

dtype('float64')

In [149]:
q3_df = df[["Country", "ConvertedComp"]].copy()

q3_df["ConvertedComp"] = pd.to_numeric(
    q3_df["ConvertedComp"],
    errors="coerce"
)

In [150]:
!pip install country_converter

Requirement already satisfied: country_converter in .\.venv\Lib\site-packages (1.3.2)
Requirement already satisfied: pandas>=1.0 in .\.venv\Lib\site-packages (from country_converter) (3.0.6)
Requirement already satisfied: numpy>=2.3.3 in .\.venv\Lib\site-packages (from pandas>=1.0->country_converter) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in .\.venv\Lib\site-packages (from pandas>=1.0->country_converter) (2.9.0.post0)
Requirement already satisfied: tzdata in .\.venv\Lib\site-packages (from pandas>=1.0->country_converter) (2026.5)
Requirement already satisfied: six>=1.5 in .\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.0->country_converter) (1.17.0)

In [151]:
import country_converter as coco

In [152]:
q3_df["Continent"] = coco.convert(
    q3_df["Country"],
    to="continent"
)

Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
Other Country (Not Listed Above) not found in regex
nan not found in ISO3
nan not found in ISO3
Other Country (Not Listed Above) not found in regex
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
Other Country (Not Listed Above) not found in regex
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
Other Country (Not Listed Above) not found in regex
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
Other Country (Not Listed Above) not found in regex
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3

In [153]:
q3_df.head(10)

                  Country  ConvertedComp Continent
0          United Kingdom            NaN    Europe
1  Bosnia and Herzegovina            NaN    Europe
2                Thailand         8820.0      Asia
3           United States        61000.0   America
4                 Ukraine            NaN    Europe
5                  Canada       366420.0   America
6                 Ukraine            NaN    Europe
7                   India            NaN      Asia
8             New Zealand        95179.0   Oceania
9                   India        13293.0      Asia

In [154]:
q3_df["Continent"].value_counts(dropna=False)

Continent
Europe       35843
America      29016
Asia         18573
Africa        2749
Oceania       2434
not found      268
Name: count, dtype: int64

In [155]:
q3_report = (
    q3_df
    .dropna(subset=["Continent", "ConvertedComp"])
    .groupby("Continent")["ConvertedComp"]
    .mean()
    .reset_index(name="AverageSalary")
)

In [156]:
q3_report

   Continent  AverageSalary
0     Africa   35045.782816
1    America  202277.425588
2       Asia   37768.549543
3     Europe   97042.157518
4    Oceania  166950.955791
5  not found   99339.803279

**4. Based on this survey, what will be the most desired programming language for the year
2020?**

In [157]:
df["LanguageDesireNextYear"].head(10)

0      C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL
1                          C++;HTML/CSS;JavaScript;SQL
2                                      Elixir;HTML/CSS
3                                  C;C#;JavaScript;SQL
4             HTML/CSS;Java;JavaScript;SQL;WebAssembly
5                                     Python;Scala;SQL
6                                  HTML/CSS;JavaScript
7    Bash/Shell/PowerShell;C;C++;Elixir;Erlang;Go;P...
8    Bash/Shell/PowerShell;C;HTML/CSS;JavaScript;Ru...
9                 C#;Go;JavaScript;Kotlin;Python;R;SQL
Name: LanguageDesireNextYear, dtype: str

In [158]:
q4_languages = df["LanguageDesireNextYear"].dropna()

In [159]:
q4_languages = q4_languages.str.split(";")

In [160]:
q4_languages

0        [C, C++, C#, Go, HTML/CSS, Java, JavaScript, P...
1                         [C++, HTML/CSS, JavaScript, SQL]
2                                       [Elixir, HTML/CSS]
3                                 [C, C#, JavaScript, SQL]
4           [HTML/CSS, Java, JavaScript, SQL, WebAssembly]
                               ...
88872                         [C++, HTML/CSS, PHP, Python]
88876                                         [JavaScript]
88877    [Bash/Shell/PowerShell, C, Go, HTML/CSS, JavaS...
88878    [C++, HTML/CSS, JavaScript, SQL, WebAssembly, ...
88882    [C, C++, C#, HTML/CSS, Java, Objective-C, SQL,...
Name: LanguageDesireNextYear, Length: 84088, dtype: object

In [161]:
all_desired_languages = [
    language
    for languages in q4_languages
    for language in languages
]

In [162]:
all_desired_languages

['C',
 'C++',
 'C#',
 'Go',
 'HTML/CSS',
 'Java',
 'JavaScript',
 'Python',
 'SQL',
 'C++',
 'HTML/CSS',
 'JavaScript',
 'SQL',
 'Elixir',
 'HTML/CSS',
 'C',
 'C#',
 'JavaScript',
 'SQL',
 'HTML/CSS',
 'Java',
 'JavaScript',
 'SQL',
 'WebAssembly',
 'Python',
 'Scala',
 'SQL',
 'HTML/CSS',
 'JavaScript',
 'Bash/Shell/PowerShell',
 'C',
 'C++',
 'Elixir',
 'Erlang',
 'Go',
 'Python',
 'SQL',
 'WebAssembly',
 'Bash/Shell/PowerShell',
 'C',
 'HTML/CSS',
 'JavaScript',
 'Ruby',
 'Rust',
 'SQL',
 'TypeScript',
 'WebAssembly',
 'Other(s):',
 'C#',
 'Go',
 'JavaScript',
 'Kotlin',
 'Python',
 'R',
 'SQL',
 'Other(s):',
 'Bash/Shell/PowerShell',
 'C++',
 'Go',
 'Python',
 'R',
 'Scala',
 'SQL',
 'Bash/Shell/PowerShell',
 'HTML/CSS',
 'JavaScript',
 'Rust',
 'SQL',
 'TypeScript',
 'WebAssembly',
 'C++',
 'Assembly',
 'Bash/Shell/PowerShell',
 'C',
 'C++',
 'C#',
 'Go',
 'HTML/CSS',
 'Java',
 'JavaScript',
 'Kotlin',
 'Objective-C',
 'PHP',
 'Python',
 'Ruby',
 'SQL',
 'Swift',
 'VBA',
 'C#',
 'HTML/CSS',
 'JavaScript',
 'TypeScript',
 'WebAssembly',
 'Other(s):',
 'Bash/Shell/PowerShell',
 'HTML/CSS',
 'Java',
 'JavaScript',
 'TypeScript',
 'WebAssembly',
 'Python',
 'R',
 'HTML/CSS',
 'JavaScript',
 'Bash/Shell/PowerShell',
 'C#',
 'HTML/CSS',
 'Java',
 'JavaScript',
 'PHP',
 'Python',
 'R',
 'SQL',
 'Bash/Shell/PowerShell',
 'C',
 'C++',
 'JavaScript',
 'Python',
 'Rust',
 'Bash/Shell/PowerShell',
 'C++',
 'HTML/CSS',
 'JavaScript',
 'Python',
 'Ruby',
 'SQL',
 'TypeScript',
 'Bash/Shell/PowerShell',
 'Go',
 'HTML/CSS',
 'Java',
 'JavaScript',
 'Kotlin',
 'Objective-C',
 'Python',
 'Ruby',
 'SQL',
 'Swift',
 'TypeScript',
 'Go',
 'HTML/CSS',
 'JavaScript',
 'PHP',
 'SQL',
 'TypeScript',
 'C#',
 'HTML/CSS',
 'JavaScript',
 'Objective-C',
 'Ruby',
 'SQL',
 'Swift',
 'TypeScript',
 'WebAssembly',
 'Clojure',
 'Dart',
 'Elixir',
 'JavaScript',
 'Python',
 'Ruby',
 'SQL',
 'TypeScript',
 'JavaScript',
 'Bash/Shell/PowerShell',
 'Clojure',
 'JavaScript',
 'Python',
 'R',
 'TypeScript',
 'C',
 'Java',
 'Python',
 'Bash/Shell/PowerShell',
 'HTML/CSS',
 'JavaScript',
 'Python',
 'Other(s):',
 'R',
 'HTML/CSS',
 'JavaScript',
 'PHP',
 'Python',
 'Ruby',
 'SQL',
 'WebAssembly',
 'Kotlin',
 'Python',
 'HTML/CSS',
 'Python',
 'Swift',
 'Other(s):',
 'C#',
 'HTML/CSS',
 'JavaScript',
 'SQL',
 'C#',
 'F#',
 'SQL',
 'TypeScript',
 'C#',
 'Bash/Shell/PowerShell',
 'HTML/CSS',
 'JavaScript',
 'SQL',
 'JavaScript',
 'PHP',
 'TypeScript',
 'C#',
 'HTML/CSS',
 'Objective-C',
 'C#',
 'Python',
 'VBA',
 'Erlang',
 'Go',
 'Scala',
 'TypeScript',
 'HTML/CSS',
 'JavaScript',
 'SQL',
 'Bash/Shell/PowerShell',
 'HTML/CSS',
 'Java',
 'JavaScript',
 'Kotlin',
 'Python',
 'SQL',
 'TypeScript',
 'HTML/CSS',
 'JavaScript',
 'Python',
 'Bash/Shell/PowerShell',
 'Dart',
 'Go',
 'HTML/CSS',
 'JavaScript',
 'Python',
 'TypeScript',
 'Rust',
 'Bash/Shell/PowerShell',
 'HTML/CSS',
 'Java',
 'JavaScript',
 'SQL',
 'TypeScript',
 'Bash/Shell/PowerShell',
 'HTML/CSS',
 'JavaScript',
 'Python',
 'Java',
 'Python',
 'Java',
 'JavaScript',
 'Kotlin',
 'Python',
 'Scala',
 'TypeScript',
 'Elixir',
 'JavaScript',
 'Python',
 'TypeScript',
 'C#',
 'F#',
 'Java',
 'Kotlin',
 'SQL',
 'HTML/CSS',
 'JavaScript',
 'PHP',
 'SQL',
 'Bash/Shell/PowerShell',
 'C++',
 'Go',
 'Kotlin',
 'Python',
 'TypeScript',
 'Go',
 'Bash/Shell/PowerShell',
 'C',
 'C++',
 'C#',
 'HTML/CSS',
 'Java',
 'JavaScript',
 'PHP',
 'Python',
 'Ruby',
 'SQL',
 'Swift',
 'Clojure',
 'Elixir',
 'Java',
 'Bash/Shell/PowerShell',
 'C++',
 'C#',
 'Rust',
 'SQL',
 'Kotlin',
 'Clojure',
 'SQL',
 'C#',
 'HTML/CSS',
 'R',
 'Rust',
 'TypeScript',
 'Elixir',
 'Go',
 'HTML/CSS',
 'Java',
 'JavaScript',
 'Kotlin',
 'Python',
 'R',
 'Scala',
 'TypeScript',
 'WebAssembly',
 'C++',
 'C#',
 'Java',
 'SQL',
 'C#',
 'HTML/CSS',
 'JavaScript',
 'Python',
 'SQL',
 'TypeScript',
 'C#',
 'HTML/CSS',
 'JavaScript',
 'PHP',
 'Ruby',
 'SQL',
 'C#',
 'HTML/CSS',
 'JavaScript',
 'SQL',
 'TypeScript',
 'SQL',
 'Java',
 'Kotlin',
 'Python',
 'HTML/CSS',
 'Java',
 'JavaScript',
 'Python',
 'TypeScript',
 'Python',
 'HTML/CSS',
 'JavaScript',
 'HTML/CSS',
 'Java',
 'JavaScript',
 'Kotlin',
 'Python',
 'C#',
 'HTML/CSS',
 'JavaScript',
 'TypeScript',
 'F#',
 'Go',
 'Python',
 'Rust',
 'Assembly',
 'Bash/Shell/PowerShell',
 'C',
 'C++',
 'Bash/Shell/PowerShell',
 'C++',
 'HTML/CSS',
 'Java',
 'JavaScript',
 'SQL',
 'Elixir',
 'Go',
 'HTML/CSS',
 'JavaScript',
 'Ruby',
 'TypeScript',
 'WebAssembly',
 'C#',
 'Java',
 'Kotlin',
 'Objective-C',
 'Bash/Shell/PowerShell',
 'C#',
 'Elixir',
 'F#',
 'HTML/CSS',
 'JavaScript',
 'Python',
 'SQL',
 'TypeScript',
 'Bash/Shell/PowerShell',
 'Go',
 'HTML/CSS',
 'JavaScript',
 'Python',
 'Rust',
 'SQL',
 'Go',
 'HTML/CSS',
 'JavaScript',
 'Kotlin',
 'Python',
 'C++',
 'C#',
 'HTML/CSS',
 'JavaScript',
 'Kotlin',
 'SQL',
 'TypeScript',
 'Bash/Shell/PowerShell',
 'HTML/CSS',
 'Python',
 'Rust',
 'SQL',
 'Bash/Shell/PowerShell',
 'C#',
 'JavaScript',
 'Objective-C',
 'Ruby',
 'SQL',
 'Swift',
 'TypeScript',
 'HTML/CSS',
 'Java',
 'Kotlin',
 'SQL',
 'C#',
 'Python',
 'Other(s):',
 'Assembly',
 'C',
 'C++',
 'C#',
 'HTML/CSS',
 'JavaScript',
 'Objective-C',
 'SQL',
 'C#',
 'JavaScript',
 'Python',
 'SQL',
 'C',
 'C++',
 'Java',
 'Python',
 'R',
 'Scala',
 'SQL',
 'Bash/Shell/PowerShell',
 'JavaScript',
 'Python',
 'R',
 'SQL',
 'HTML/CSS',
 'Java',
 'JavaScript',
 'PHP',
 'SQL',
 'TypeScript',
 'Python',
 'SQL',
 'C',
 'C++',
 'Elixir',
 'HTML/CSS',
 'JavaScript',
 'Ruby',
 'SQL',
 'TypeScript',
 'Bash/Shell/PowerShell',
 'HTML/CSS',
 'JavaScript',
 'SQL',
 'C',
 'C++',
 'Elixir',
 'Go',
 'Ruby',
 'WebAssembly',
 'Clojure',
 'F#',
 'Java',
 'TypeScript',
 'Bash/Shell/PowerShell',
 'HTML/CSS',
 'JavaScript',
 'HTML/CSS',
 'JavaScript',
 'Python',
 'Assembly',
 'Go',
 'Rust',
 'WebAssembly',
 'C++',
 'Python',
 'Rust',
 'C#',
 'HTML/CSS',
 'JavaScript',
 'SQL',
 'Python',
 'SQL',
 'Bash/Shell/PowerShell',
 'C#',
 'HTML/CSS',
 'JavaScript',
 'Python',
 'SQL',
 'VBA',
 'Assembly',
 'Bash/Shell/PowerShell',
 'C',
 'C++',
 'C#',
 'F#',
 'Go',
 'Java',
 'JavaScript',
 'Kotlin',
 'Objective-C',
 'PHP',
 'Python',
 'R',
 'Ruby',
 'SQL',
 'Swift',
 'WebAssembly',
 'Bash/Shell/PowerShell',
 'C',
 'C++',
 'JavaScript',
 'Python',
 'HTML/CSS',
 'Java',
 'JavaScript',
 'SQL',
 'Scala',
 'Other(s):',
 'C#',
 'HTML/CSS',
 'JavaScript',
 'TypeScript',
 'Bash/Shell/PowerShell',
 'C',
 'C',
 'C++',
 'C#',
 'HTML/CSS',
 'Java',
 'JavaScript',
 'Kotlin',
 'Python',
 'SQL',
 'Swift',
 'Elixir',
 'HTML/CSS',
 'Python',
 'Ruby',
 'Rust',
 'Swift',
 'Dart',
 'Go',
 'Kotlin',
 'R',
 'TypeScript',
 'Assembly',
 'Bash/Shell/PowerShell',
 'C++',
 'Python',
 'JavaScript',
 'Python',
 'TypeScript',
 'Java',
 'Python',
 'Bash/Shell/PowerShell',
 'C++',
 'Dart',
 'HTML/CSS',
 'Java',
 'JavaScript',
 'Kotlin',
 'Python',
 'R',
 'Scala',
 'Swift',
 'Rust',
 'Bash/Shell/PowerShell',
 'C',
 'Go',
 'Python',
 'Rust',
 'Bash/Shell/PowerShell',
 'Go',
 'Ruby',
 'C++',
 'Clojure',
 'Go',
 'Python',
 'R',
 'Rust',
 'Bash/Shell/PowerShell',
 'C#',
 'Clojure',
 'Erlang',
 'Go',
 'HTML/CSS',
 'Kotlin',
 'Python',
 'Ruby',
 'Scala',
 'SQL',
 'Ruby',
 'Swift',
 'C++',
 'C#',
 'HTML/CSS',
 'Objective-C',
 'Python',
 'Swift',
 'TypeScript',
 'JavaScript',
 'WebAssembly',
 'C++',
 'HTML/CSS',
 'SQL',
 'HTML/CSS',
 'JavaScript',
 'TypeScript',
 'C++',
 'Java',
 'Kotlin',
 'Python',
 'SQL',
 'Go',
 'Python',
 'Bash/Shell/PowerShell',
 'C#',
 'HTML/CSS',
 'PHP',
 'Python',
 'SQL',
 'Dart',
 'Java',
 'JavaScript',
 'Kotlin',
 'PHP',
 'Python',
 'SQL',
 'Bash/Shell/PowerShell',
 'HTML/CSS',
 'Java',
 'JavaScript',
 'Python',
 'SQL',
 'TypeScript',
 'C#',
 'Python',
 'C',
 'Clojure',
 'F#',
 'Java',
 'Python',
 'Rust',
 'TypeScript',
 'HTML/CSS',
 'Java',
 'SQL',
 'C',
 'C#',
 'R',
 'SQL',
 'Swift',
 'Rust',
 'Kotlin',
 'HTML/CSS',
 'JavaScript',
 'Python',
 'TypeScript',
 'WebAssembly',
 'Bash/Shell/PowerShell',
 'C++',
 'C#',
 'Go',
 'Java',
 'Kotlin',
 'Python',
 'SQL',
 'TypeScript',
 'Kotlin',
 'C',
 'C++',
 'Java',
 'Python',
 'Bash/Shell/PowerShell',
 'HTML/CSS',
 'JavaScript',
 'TypeScript',
 'Bash/Shell/PowerShell',
 'C#',
 'HTML/CSS',
 'JavaScript',
 'SQL',
 'TypeScript',
 'Java',
 'SQL',
 'Bash/Shell/PowerShell',
 'Clojure',
 'Go',
 'HTML/CSS',
 'JavaScript',
 'Python',
 'C#',
 'F#',
 'Rust',
 'TypeScript',
 'Go',
 'HTML/CSS',
 'JavaScript',
 'PHP',
 'Dart',
 'Java',
 'Kotlin',
 'Objective-C',
 'SQL',
 'Assembly',
 'Bash/Shell/PowerShell',
 'C#',
 'HTML/CSS',
 'JavaScript',
 'SQL',
 'Other(s):',
 'C#',
 'F#',
 'HTML/CSS',
 'JavaScript',
 'Python',
 'SQL',
 'TypeScript',
 'Bash/Shell/PowerShell',
 'C#',
 'Python',
 'SQL',
 'Bash/Shell/PowerShell',
 'HTML/CSS',
 'Java',
 'JavaScript',
 'Ruby',
 'Rust',
 'SQL',
 'Swift',
 'C#',
 'TypeScript',
 'Bash/Shell/PowerShell',
 'C',
 'C++',
 'Erlang',
 'Python',
 'C',
 'C++',
 'HTML/CSS',
 'Java',
 'JavaScript',
 'PHP',
 'Python',
 'SQL',
 'Clojure',
 'Go',
 'HTML/CSS',
 'JavaScript',
 'Bash/Shell/PowerShell',
 'Clojure',
 'JavaScript',
 'HTML/CSS',
 'JavaScript',
 'SQL',
 'JavaScript',
 'PHP',
 'SQL',
 'TypeScript',
 'C',
 'C++',
 'HTML/CSS',
 'JavaScript',
 'PHP',
 'Python',
 'Assembly',
 'Bash/Shell/PowerShell',
 'C',
 'C++',
 'C#',
 'HTML/CSS',
 'Java',
 'JavaScript',
 'Kotlin',
 'PHP',
 'Python',
 'SQL',
 'C++',
 'HTML/CSS',
 'Java',
 'JavaScript',
 'Python',
 'SQL',
 'C#',
 'Python',
 'SQL',
 'JavaScript',
 'PHP',
 'Python',
 'Ruby',
 'SQL',
 'TypeScript',
 'C#',
 'HTML/CSS',
 'JavaScript',
 'Kotlin',
 'Swift',
 'C#',
 'HTML/CSS',
 'Java',
 'JavaScript',
 'PHP',
 'SQL',
 'HTML/CSS',
 'JavaScript',
 'Rust',
 'TypeScript',
 'Bash/Shell/PowerShell',
 'C++',
 'Elixir',
 'Go',
 'HTML/CSS',
 'JavaScript',
 'Kotlin',
 'Rust',
 'SQL',
 'TypeScript',
 'WebAssembly',
 'Dart',
 'Java',
 'Kotlin',
 'Swift',
 'C',
 'C++',
 'Java',
 'Kotlin',
 'Python',
 'Rust',
 'TypeScript',
 'Java',
 'Kotlin',
 'Assembly',
 'C++',
 'HTML/CSS',
 'Java',
 'JavaScript',
 'Python',
 'C',
 'HTML/CSS',
 'JavaScript',
 'Python',
 'Ruby',
 'Scala',
 'SQL',
 'C++',
 'C#',
 'Python',
 'R',
 'SQL',
 'VBA',
 'Go',
 'Python',
 'SQL',
 'HTML/CSS',
 'Python',
 'R',
 'Bash/Shell/PowerShell',
 'HTML/CSS',
 'JavaScript',
 'Rust',
 'SQL',
 'WebAssembly',
 'Bash/Shell/PowerShell',
 'Python',
 'Scala',
 'Bash/Shell/PowerShell',
 'C#',
 'HTML/CSS',
 'JavaScript',
 'Ruby',
 'SQL',
 'TypeScript',
 'Bash/Shell/PowerShell',
 'C',
 'HTML/CSS',
 'Java',
 'PHP',
 'C#',
 'TypeScript',
 'Other(s):',
 'F#',
 'HTML/CSS',
 'JavaScript',
 'Python',
 'Rust',
 'SQL',
 'TypeScript',
 'R',
 'SQL',
 'Java',
 'Python',
 'SQL',
 'Go',
 'HTML/CSS',
 'Python',
 'Bash/Shell/PowerShell',
 'C',
 'C++',
 'Objective-C',
 'Python',
 'Assembly',
 'Rust',
 'WebAssembly',
 'C++',
 'HTML/CSS',
 'Java',
 'JavaScript',
 'Objective-C',
 'Python',
 'HTML/CSS',
 'JavaScript',
 'PHP',
 'Python',
 'Scala',
 'SQL',
 'Dart',
 'Java',
 'JavaScript',
 'Kotlin',
 'Other(s):',
 'Bash/Shell/PowerShell',
 'Python',
 'SQL',
 'Go',
 'Kotlin',
 'Python',
 'WebAssembly',
 'Other(s):',
 'HTML/CSS',
 'Java',
 'JavaScript',
 'PHP',
 'Go',
 'JavaScript',
 'Kotlin',
 'Python',
 'Python',
 'R',
 'Other(s):',
 'Rust',
 'C',
 'Java',
 'Python',
 'R',
 'Scala',
 'Go',
 'HTML/CSS',
 'JavaScript',
 'TypeScript',
 'C#',
 'Go',
 'C#',
 'HTML/CSS',
 'Java',
 'JavaScript',
 'Kotlin',
 'Python',
 'SQL',
 'C++',
 'HTML/CSS',
 'Java',
 'JavaScript',
 'PHP',
 'Python',
 'SQL',
 'HTML/CSS',
 'JavaScript',
 'Other(s):',
 'Java',
 'Kotlin',
 'Go',
 'Rust',
 'C++',
 'C#',
 'HTML/CSS',
 'Java',
 'JavaScript',
 'PHP',
 ...]

In [163]:
language_counts = pd.Series(all_desired_languages).value_counts()

In [164]:
language_counts.head()

JavaScript    44739
Python        40006
HTML/CSS      36645
SQL           33566
TypeScript    23720
Name: count, dtype: int64

In [165]:
most_desired_language = language_counts.idxmax()
most_desired_count = language_counts.max()

print("Most desired programming language for 2020:", most_desired_language)
print("Number of developers:", most_desired_count)

Most desired programming language for 2020: JavaScript
Number of developers: 44739

**5. Generate the report for the people who code as a hobby based on their gender
and continent.**

In [166]:
df["Gender"].value_counts(dropna=False).head(20)

Gender
Man                                                            77919
Woman                                                           6344
NaN                                                             3477
Non-binary, genderqueer, or gender non-conforming                597
Man;Non-binary, genderqueer, or gender non-conforming            181
Woman;Non-binary, genderqueer, or gender non-conforming          163
Woman;Man                                                        132
Woman;Man;Non-binary, genderqueer, or gender non-conforming       70
Name: count, dtype: int64

In [167]:
def clean_gender(gender):
    if pd.isna(gender):
        return "OTHERS"

    gender = gender.strip().upper()

    if gender == "MAN":
        return "MAN"
    elif gender == "WOMAN":
        return "WOMAN"
    else:
        return "OTHERS"

In [168]:
df["GenderCategory"] = df["Gender"].apply(clean_gender)

In [169]:
df["GenderCategory"].value_counts()

GenderCategory
MAN       77919
WOMAN      6344
OTHERS     4620
Name: count, dtype: int64

In [170]:
q5_df = df[
    ["Country", "Hobbyist", "GenderCategory"]
].copy()

q5_df["Continent"] = coco.convert(
    q5_df["Country"],
    to="continent"
)

Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
Other Country (Not Listed Above) not found in regex
nan not found in ISO3
nan not found in ISO3
Other Country (Not Listed Above) not found in regex
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
Other Country (Not Listed Above) not found in regex
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
Other Country (Not Listed Above) not found in regex
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
Other Country (Not Listed Above) not found in regex
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3

In [171]:
q5_df["Hobbyist"].value_counts(dropna=False)

Hobbyist
Yes    71257
No     17626
Name: count, dtype: int64

In [172]:
q5_hobbyists = q5_df[
    q5_df["Hobbyist"] == "Yes"
].copy()

In [173]:
q5_report = (
    q5_hobbyists
    .dropna(subset=["Continent"])
    .groupby(["Continent", "GenderCategory"])
    .size()
    .reset_index(name="HobbyistCount")
)

In [174]:
q5_report

    Continent GenderCategory  HobbyistCount
0      Africa            MAN           1928
1      Africa         OTHERS            110
2      Africa          WOMAN            125
3     America            MAN          20291
4     America         OTHERS           1163
5     America          WOMAN           1623
6        Asia            MAN          12692
7        Asia         OTHERS           1042
8        Asia          WOMAN            768
9      Europe            MAN          26831
10     Europe         OTHERS           1167
11     Europe          WOMAN           1405
12    Oceania            MAN           1800
13    Oceania         OTHERS            113
14    Oceania          WOMAN            100
15  not found            MAN             77
16  not found         OTHERS             17
17  not found          WOMAN              5

****6. Generate the report for job and career satisfaction of developers based on their
gender and continent.****

In [175]:
q6_df = df[
    ["Country", "GenderCategory", "JobSat", "CareerSat"]
].copy()

In [176]:
q6_df["Continent"] = coco.convert(
    q6_df["Country"],
    to="continent"
)

Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
Other Country (Not Listed Above) not found in regex
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
Other Country (Not Listed Above) not found in regex
nan not found in ISO3
nan not found in ISO3
Other Country (Not Listed Above) not found in regex
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
Other Country (Not Listed Above) not found in regex
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
Other Country (Not Listed Above) not found in regex
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
Other Country (Not Listed Above) not found in regex
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3
nan not found in ISO3

In [177]:
q6_df["JobSat"].value_counts(dropna=False)

JobSat
Slightly satisfied                    24207
Very satisfied                        22452
NaN                                   17895
Slightly dissatisfied                 10752
Neither satisfied nor dissatisfied     8720
Very dissatisfied                      4857
Name: count, dtype: int64

In [178]:
q6_df["CareerSat"].value_counts(dropna=False)

CareerSat
Very satisfied                        29173
Slightly satisfied                    25018
NaN                                   16036
Slightly dissatisfied                  7670
Neither satisfied nor dissatisfied     7252
Very dissatisfied                      3734
Name: count, dtype: int64

In [179]:
job_satisfaction_report = (
    q6_df
    .dropna(subset=["Continent", "JobSat"])
    .groupby(
        ["Continent", "GenderCategory", "JobSat"]
    )
    .size()
    .reset_index(name="DeveloperCount")
)

In [180]:
job_satisfaction_report

,Continent,GenderCategory,JobSat,DeveloperCount
0,Africa,MAN,Neither satisfied nor dissatisfied,242
1,Africa,MAN,Slightly dissatisfied,259
2,Africa,MAN,Slightly satisfied,540
3,Africa,MAN,Very dissatisfied,137
4,Africa,MAN,Very satisfied,352
...,...,...,...,...
84,not found,WOMAN,Neither satisfied nor dissatisfied,1
85,not found,WOMAN,Slightly dissatisfied,1
86,not found,WOMAN,Slightly satisfied,3
87,not found,WOMAN,Very dissatisfied,1
88,not found,WOMAN,Very satisfied,3